export const FETCH_MEMBERS_REQUEST = "FETCH_MEMBERS_REQUEST"
export const FETCH_MEMBERS_SUCCESS = "FETCH_MEMBERS_SUCCESS"
export const FETCH_MEMBERS_FAILED= "FETCH_MEMBERS_FAILED"
export const SEARCH_MEMBER = "SEARCH_MEMBER"
// export const DELETE_MEMBER_REQUEST = "DELETE_MEMBER_REQUEST"
export const DELETE_MEMBER_SUCCESS = "DELETE_MEMBER_SUCCESS"

export const ADD_MEMBER= "ADD_MEMBER"